server:
  port:
    8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test
    password: root
  jpa:
    hibernate:
      ddl-auto: update
